const siteMetadata = {
  title: "Evan Maus | Economics, Data Science & AI",
  author: "Evan Maus",
  headerTitle: "Evan Maus",
  description: "Evan Maus - UC Berkeley Economics & Data Science student, full-stack developer, and quantitative researcher. Building production web applications, ML systems, and trading tools. Expertise in Next.js, Python, React, PyTorch, and applied machine learning. Available for internships and collaborations.",
  language: "en-us",
  theme: "system",
  siteUrl: "http://blog.evwillow.com",
  siteLogo: "/headshot.jpg",
  socialBanner: "/headshot.jpg", // Using existing headshot as social banner
  defaultBlogImage: "/headshot.jpg", // Default image for blog posts without featured images
  email: "evan_maus@berkeley.edu",
  phone: "740-971-8762",
  github: "https://github.com/evwillow",
  linkedin: "https://linkedin.com/in/evwillow",
  twitter: "https://x.com/evwillow1",
  location: "Berkeley, CA",
  university: "UC Berkeley",
  graduation: "May 2027",
  locale: "en-US",
  keywords: [
    "Evan Maus",
    "evan_maus@berkeley.edu",
    "UC Berkeley",
    "Berkeley Economics",
    "Berkeley Data Science",
    "Economics student",
    "Data Science student",
    "Computer Science minor",
    "Full stack developer",
    "Fullstack developer",
    "Next.js developer",
    "TypeScript developer",
    "React developer",
    "Python developer",
    "JavaScript developer",
    "Machine Learning engineer",
    "ML engineer",
    "AI researcher",
    "Quantitative researcher",
    "Quantitative finance",
    "Trading systems",
    "Breakout trading",
    "Algorithmic trading",
    "PyTorch",
    "TensorFlow",
    "FastAPI",
    "Supabase",
    "DigitalOcean",
    "Docker",
    "Freelance developer",
    "Web development",
    "Software engineering",
    "Data pipelines",
    "Applied ML",
    "Energy efficiency research",
    "LLM benchmarking",
    "NLP research",
    "Econometrics",
    "Game Theory",
    "Portfolio optimization",
    "Student portfolio",
    "Berkeley student",
    "Startup experience",
    "Product-led entrepreneurship",
    "Climate software",
    "Sustainability tech",
    "Climate action",
    "Eagle Scout",
    "LinkedIn",
    "GitHub",
    "Personal website",
    "Professional portfolio",
    "Tech blog",
    "Engineering blog"
  ],
  // Additional SEO metadata
  category: "Technology & Education",
  type: "website",
  twitterHandle: "@evwillow1",
  facebookAppId: "",
  googleAnalyticsId: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID,
  googleSiteVerification: process.env.NEXT_PUBLIC_GOOGLE_VERIFICATION,
}

export default siteMetadata
