const siteMetadata = {
  title: "Evan W Maus | Economics, Data Science & AI",
  author: "Evan W Maus",
  headerTitle: "Evan W Maus",
  description: "UC Berkeley student majoring in Economics & Data Science with a minor in Computer Science. Building solutions at the intersection of AI, finance, and sustainability. Fullstack developer, quantitative trader, and researcher.",
  language: "en-us",
  theme: "system",
  siteUrl: "https://evwillow.com",
  siteLogo: "/logo.png",
  socialBanner: "/social-banner.png",
  email: "evan_maus@berkeley.edu",
  github: "https://github.com/evwillow",
  linkedin: "https://linkedin.com/in/evwillow",
  twitter: "https://x.com/evwillow1",
  location: "San Francisco, CA",
  university: "UC Berkeley",
  graduation: "May 2027",
  locale: "en-US",
  keywords: [
    "Evan Maus",
    "UC Berkeley",
    "Economics",
    "Data Science",
    "Computer Science",
    "AI",
    "Machine Learning",
    "Quantitative Trading",
    "Fullstack Developer",
    "Next.js",
    "Python",
    "Finance",
    "Sustainability"
  ],
}

export default siteMetadata
